services:
  - type: web
    name: football-predictions
    runtime: python3
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --workers 1 --timeout 120 --max-requests 1000
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: "1"
      # ⚠️ IMPORTANT: Configurez cette variable dans le dashboard Render
      # Ne pas mettre la clé API ici directement !
      - key: API_SPORTS_KEY
        sync: false  # Indique que cette variable doit être configurée manuellement
    healthCheckPath: /health
    numInstances: 1
    autoDeploy: true